apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-server
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-repo-server
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: platform-repo-server
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-applicationset-controller
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-applicationset-controller
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-notifications-controller
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
