apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-oidc
  namespace: argocd
$patch: delete
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: platform-gitops-repository
  namespace: argocd
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-server
  namespace: argocd
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-repo-server
  namespace: argocd
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-applicationset-controller
  namespace: argocd
$patch: delete
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: platform-notifications-controller
  namespace: argocd
$patch: delete
