apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-operator-controller-manager
  namespace: argocd-operator-system
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: WATCH_NAMESPACE
              value: argocd,gitops-smoke
              valueFrom: null
